steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/n8n', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/n8n']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'n8n',
        '--image',
        'gcr.io/$PROJECT_ID/n8n',
        '--platform',
        'managed',
        '--region',
        'asia-southeast2',
        '--allow-unauthenticated',
      ]
images:
  - 'gcr.io/$PROJECT_ID/n8n'
